### ISSUE TITLE
printAutostartStatus

### ISSUE THREAD

**Issue by pnzr00t** [mishamyrt/runon#3]
https://github.com/mishamyrt/runif/blob/0625d27fd35fe13477b30a1c9442c6a07e9e010c/Sources/Commands/Autostart.swift#L17

Не уверен что тебе нужен static, но да ладно ) 

``` swift
    static func printAutostartStatus(enabled: Bool) { 
        var message = "Autostart is "

        message += enabled ? "enabled" : "disabled"
        
        debugPrint(message) // DebugPrint, может выдать доп информацию в частности о типе переменной, но это вкусовщина 
    }
```

**Comment by mishamyrt** [comment]
Увы, `ParsableCommand` может иметь только статичные кастомные методы
